const PLACEHOLDER_BASE = "https://placehold.co";
const PLACEHOLDER_COLOR = "cccccc/ffffff";
const PLACEHOLDER_BRAND = "003D8D/FECE00";

export const PLACEHOLDERS = {
  DOSEN: `${PLACEHOLDER_BASE}/400x500/${PLACEHOLDER_COLOR}?text=Foto+Dosen`,
  MAHASISWA: `${PLACEHOLDER_BASE}/400x500/${PLACEHOLDER_COLOR}?text=Foto+Mahasiswa`,
  BERITA: `${PLACEHOLDER_BASE}/600x338/${PLACEHOLDER_COLOR}?text=No+Image`,
  BERITA_ERROR: `${PLACEHOLDER_BASE}/600x338/${PLACEHOLDER_COLOR}?text=Gambar+Error`,
  BERITA_DETAIL: `${PLACEHOLDER_BASE}/1200x675/${PLACEHOLDER_COLOR}?text=No+Image`,
  BERITA_DETAIL_ERROR: `${PLACEHOLDER_BASE}/1200x675/${PLACEHOLDER_COLOR}?text=Gambar+Tidak+Ditemukan`,
  BERITA_THUMB: `${PLACEHOLDER_BASE}/150x150/${PLACEHOLDER_COLOR}?text=Img`,
  GALERI: (id) => `${PLACEHOLDER_BASE}/600x400/${PLACEHOLDER_COLOR}?text=Foto+${id}`,
  GEDUNG: `${PLACEHOLDER_BASE}/1200x675/${PLACEHOLDER_COLOR}?text=Gedung+UPS`,
  NO_IMAGE: `${PLACEHOLDER_BASE}/400x500/${PLACEHOLDER_COLOR}?text=No+Image`,
  LOGO_IF: `${PLACEHOLDER_BASE}/40x40/${PLACEHOLDER_BRAND}?text=IF`,
  LOGO_UPS: `${PLACEHOLDER_BASE}/120x40/${PLACEHOLDER_BRAND}?text=UPS`,
  HERO: (index) => `${PLACEHOLDER_BASE}/1920x1080/${PLACEHOLDER_BRAND}?text=Gedung+UPS+${index + 1}`,
  ORGANISASI: (name) => `${PLACEHOLDER_BASE}/96x96/${PLACEHOLDER_COLOR}?text=${name.substring(0, 2)}`,
};
