const PLACEHOLDER_BASE = "https://placehold.co";
const PLACEHOLDER_COLOR = "cccccc/ffffff";

export const PLACEHOLDERS = {
  DOSEN: `${PLACEHOLDER_BASE}/400x500/${PLACEHOLDER_COLOR}?text=Foto+Dosen`,
  MAHASISWA: `${PLACEHOLDER_BASE}/400x500/${PLACEHOLDER_COLOR}?text=Foto+Mahasiswa`,
  BERITA: `${PLACEHOLDER_BASE}/600x338/${PLACEHOLDER_COLOR}?text=No+Image`,
  BERITA_ERROR: `${PLACEHOLDER_BASE}/600x338/${PLACEHOLDER_COLOR}?text=Gambar+Error`,
  BERITA_DETAIL: `${PLACEHOLDER_BASE}/1200x675/${PLACEHOLDER_COLOR}?text=No+Image`,
  BERITA_DETAIL_ERROR: `${PLACEHOLDER_BASE}/1200x675/${PLACEHOLDER_COLOR}?text=Gambar+Tidak+Ditemukan`,
  BERITA_THUMB: `${PLACEHOLDER_BASE}/150x150/${PLACEHOLDER_COLOR}?text=Img`,
  GALERI: (id) => `${PLACEHOLDER_BASE}/600x400/${PLACEHOLDER_COLOR}?text=Foto+${id}`,
  GEDUNG: `${PLACEHOLDER_BASE}/1200x675/${PLACEHOLDER_COLOR}?text=Gedung+UPS`,
  NO_IMAGE: `${PLACEHOLDER_BASE}/400x500/${PLACEHOLDER_COLOR}?text=No+Image`,
};
